from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

from ..models import Comparison, FrameDecode, GlossaryEntry, PortEntry, SearchResult, SubnetResult, Technology


class ToolkitService(ABC):
    """The application's only backend boundary. UI code calls this interface exclusively."""

    @abstractmethod
    def list_technologies(self, category: str | None = None) -> list[Technology]: ...
    @abstractmethod
    def get_technology(self, technology_id: str) -> Technology: ...
    @abstractmethod
    def list_categories(self) -> list[str]: ...
    @abstractmethod
    def search(self, query: str) -> list[SearchResult]: ...
    @abstractmethod
    def compare(self, left_id: str, right_id: str) -> Comparison: ...
    @abstractmethod
    def hierarchy(self, technology_id: str) -> dict[str, Any]: ...
    @abstractmethod
    def list_ports(self, query: str = "") -> list[PortEntry]: ...
    @abstractmethod
    def list_glossary(self, query: str = "") -> list[GlossaryEntry]: ...
    @abstractmethod
    def list_troubleshooting(self) -> dict[str, list[str]]: ...
    @abstractmethod
    def favorites(self) -> set[str]: ...
    @abstractmethod
    def set_favorite(self, item_id: str, enabled: bool) -> None: ...
    @abstractmethod
    def number_conversion(self, value: str, numeric_format: str) -> dict[str, Any]: ...
    @abstractmethod
    def ieee_to_hex(self, value: float, precision: int) -> str: ...
    @abstractmethod
    def ieee_from_hex(self, value: str, precision: int) -> float: ...
    @abstractmethod
    def endian_decode(self, value: str) -> dict[str, Any]: ...
    @abstractmethod
    def modbus_address(self, reference: str) -> dict[str, Any]: ...
    @abstractmethod
    def modbus_registers(self, registers: list[int]) -> dict[str, Any]: ...
    @abstractmethod
    def modbus_crc(self, value: str) -> dict[str, str]: ...
    @abstractmethod
    def modbus_frame(self, value: str) -> FrameDecode: ...
    @abstractmethod
    def subnet(self, ip: str, mask_or_cidr: str) -> SubnetResult: ...
    @abstractmethod
    def same_subnet(self, ip_a: str, ip_b: str, mask_or_cidr: str) -> dict[str, Any]: ...
    @abstractmethod
    def validate_ips(self, values: list[str], mask_or_cidr: str | None = None) -> list[dict[str, Any]]: ...
    @abstractmethod
    def commands(self, host: str, port: int | None = None) -> dict[str, list[str]]: ...

